# pre-commit is a framework for managing and maintaining multi-language pre-commit hooks.
# https://pre-commit.com/
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
        name: '[.] check json'
      - id: check-toml
        name: '[.] check toml'
      - id: check-yaml
        name: '[.] check yaml'
      - id: end-of-file-fixer
        name: '[.] end of file fixer'
      - id: trailing-whitespace
        name: '[.] trailing whitespace'
      - id: pretty-format-json
        name: '[.] format json'
        args:
          - --autofix
          - --indent=4
          - --no-sort-keys

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-format
        name: '[py] format'
        args:
          - --config
          - ruff.toml

      - id: ruff-check
        name: '[py] lint'
        args:
          - --fix
          - --config
          - ruff.toml
